Cadastro usuario
wandersonmaceds/mercadolivre-spring pull request #1
Opened 2021-01-13 12:29 UTC by wandersonmaceds

Cadastro de usuário, está funcionando, não tem uma super-tela (ainda, vou fazer depois). 

Pontos de atenção:

1. Os erros não estavam sendo impressos até eu usar o `<form:form modelAttribute>` apontando para o objeto do request.
2. Por algum motivo a validação do `@Email` não está funcionando. (não sei por que).

2021-01-13 18:58 UTC, alexandreaquiles reviewed
A classe `UserDTO` não está sendo utilizado. Pode ser removida.

2021-01-13 18:58 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/user/UserForm.java
> +    @NotNull
Faltou impedir email/login em branco:

```suggestion
    @NotBlank
```

2021-01-13 18:58 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/user/UserController.java
> +    public String newUser(@Valid @ModelAttribute("user") UserForm user, BindingResult bindingResult) {
```suggestion
    public String newUser(@Valid UserForm userForm, BindingResult bindingResult) {
```

2021-01-13 18:59 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/user/UserForm.java
> +    @NotNull
A senha não deveria estar em branco:

```suggestion
    @NotBlank
```

2021-01-13 19:08 UTC, alexandreaquiles commented on src/main/webapp/WEB-INF/views/user/form.jsp
> +    </form:form>
Removendo o `@ModelAttribute`, dá pra fazer assim aqui:

```
<form action="/user/new" method="post">
        <div class="input-group">
            <label for="email">Email</label>
            <input id="email" name="email" type="email" placeholder="jorge.vinicius@email.com">
            <form:errors path="userForm.email" />
        </div>

        <div class="input-group">
            <label for="password">Senha: <small>6 caracteres no mínimo</small></label>
            <input id="password" name="password" type="password" placeholder="******">
            <form:errors path="userForm.password" />
        </div>

        <button type="submit">Criar conta</button>
    </form>
    ```

2021-01-13 19:31 UTC, alexandreaquiles commented
O que pode ser modificador de acesso padrão (sem ser public)?
(p/ classes, métodos, construtores, ...)

2021-01-13 19:33 UTC, alexandreaquiles commented
Evitar `@Autowired` em atributos.

```
    private final UserRepository userRepository;

    public UserController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }
  ```

2021-01-13 19:34 UTC, alexandreaquiles commented
No `ok.jsp` tirar comentários desnecessários.

2021-01-13 19:35 UTC, alexandreaquiles commented
Usar redirect after POST.

2021-01-20 14:48 UTC, alexandreaquiles requested changes
Ficou muito bom, @wandersonmaceds!

A validação do front ficou :top:!

Peguei um typo.

E mais algumas coisas:
- prefiro não colocar o `LocalDateTime.now()` no setter com `@PrePersist`. Acho que colocar um atributo com valor padrão fica mais simples e não tá amarrado com o framework de persistência. Vai ter o caso que, ao busca, vai inicializar o objeto com a hora atual e depois mudar com a do BD, mas não acho isso um problema. Acho que criar o objeto num estado válido padrão é mais interessante!
- dá pra colocar mais algumas coisas como modificador de acesso default, accessível apenas no mesmo pacote. Creio que só os getters e setters do UserForm que precisam ser públicos.

2021-01-20 14:48 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/secutiry/WebSecurityConfiguration.java
> +package br.com.mercadolivre.loja.secutiry;
Typo no nome do pacote

```suggestion
package br.com.mercadolivre.loja.securiyy;
```

2021-01-20 14:48 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/user/UserController.java
>  @Controller()
Em Java, não é comum colocarmos o `()` numa anotação sem mudança de parâmetros. Acho que é assim no Nest, né?

```suggestion
@Controller
```

2021-01-20 14:48 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/user/User.java
>      public User() {}
Os construtores podem ser com modificador default.

```suggestion
    User() {}
```

2021-01-20 14:48 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/user/User.java
>      public User(String login, String password) {
Pode usar o construtor default aqui.

```suggestion
    User(String login, String password) { }
```

2021-01-20 14:48 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/user/UserForm.java
>      public User toModel() {
Aqui pode ter o modificador acesso default.

```suggestion
    User toModel() {
```

2021-01-20 17:17 UTC, wandersonmaceds commented on src/main/java/br/com/mercadolivre/loja/user/UserController.java
>  @Controller()
Não lembro com exatidão, acho que lá é necessário usar. Aqui fui no automático.

2021-01-20 19:10 UTC, alexandreaquiles commented on src/main/java/br/com/mercadolivre/loja/user/UserForm.java
>          this.password = passwordEncoder.encode(password);
Um comentário nesse trecho de criação do PasswordEncoder.

É interessante crriar uma  classe com um método (estático mesmo) que fica responsável por instanciar o PasswordEncoder. Ficaria no pacote `security`.

Aqui, você apenas usaria o `PasswordEnconder`, sem necessariamente saber que é bcrypt.

2021-01-22 14:45 UTC, alexandreaquiles approved these changes
Aprovando!

2021-03-10 11:54 UTC, merged